"""Add Assessment model and update Class/Grade

Revision ID: 5c9a0c0605f2
Revises: 79f509abebdc
Create Date: 2025-10-31 20:22:08.715082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c9a0c0605f2'
down_revision: Union[str, Sequence[str], None] = '79f509abebdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_method', sa.Enum('arithmetic', 'weighted', name='calculation_methods'), server_default='arithmetic', nullable=False))

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_grades_assessment_id', 'assessments', ['assessment_id'], ['id'])
        batch_op.drop_column('assignment_name')
        batch_op.drop_column('course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('assignment_name', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_grades_course_id', 'courses', ['course_id'], ['id'])
        batch_op.drop_column('assessment_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('calculation_method')

    op.drop_table('assessments')
    # ### end Alembic commands ###
